# 安装 / 更新 Windows 计划任务，让论文推送自动跟随开机。
#
# 解决什么问题：
#   GitHub 禁用 fork 仓库的 schedule（cron），所以推送靠本机触发。
#   固定时刻触发的问题是 —— 电脑那时若在睡眠/关机就会漏掉。
#   本方案用「开机 / 登录 / 定点」多路触发 + 当天去重，任何一种能赶上就发。
#
# 触发器设计（四个）：
#   1. 开机 +3 分钟       —— 延迟等代理软件启动
#   2. 登录 +3 分钟       —— 覆盖睡眠唤醒、快速用户切换
#   3. 周一 10:00         —— 覆盖「周日晚上不关机、周一整天无开关机操作」
#   4. 周四 10:00         —— 同上
#
# 去重：trigger_workflow.ps1 内置"当天是否已推送"判断，
#       上述触发器共用同一标记，因此一天只会发一次。
#
# 曾有一个「10:30 起每 30 分钟重试」的触发器，已按需求删除：
# 网络失败时当天收不到邮件，但 10:00 的定点触发已经覆盖了
# 「当天开过机」这个更常见的场景，反复重试的边际收益很低。
#
# 用法：.\setup_scheduler.ps1

$ErrorActionPreference = 'Stop'

$scriptDir  = $PSScriptRoot
$mainScript = Join-Path $scriptDir 'trigger_workflow.ps1'
$tokenFile  = Join-Path $scriptDir 'github_token.txt'
$taskName     = 'ZoteroArxivDaily'
$keepTaskName = 'ZoteroArxivKeepAlive'

if (-not (Test-Path $mainScript)) { throw "找不到 trigger_workflow.ps1" }

# --- 1. Token 检查 ---
if (-not (Test-Path $tokenFile)) {
    Write-Host "`n需要先创建 token 文件。" -ForegroundColor Yellow
    Write-Host "1) 打开 https://github.com/settings/tokens/new"
    Write-Host "2) Note 填 zotero-daily-trigger，Expiration 选 90 days"
    Write-Host "3) Permissions -> Repository permissions -> 勾选 repo"
    Write-Host "4) 生成后复制 ghp_... 开头的 token"
    Write-Host ''
    Read-Host "准备好后按回车继续（会自动打开记事本）" | Out-Null
    notepad $tokenFile
    Write-Host "`n请粘贴 token 并保存记事本，然后按回车继续" -ForegroundColor Yellow
    Read-Host | Out-Null
}
$token = (Get-Content $tokenFile -Raw).Trim()
if ($token -notmatch '^ghp_') { throw "github_token.txt 内容无效，应为 ghp_ 开头的 token" }

# --- 2. 清理旧任务 ---
foreach ($tn in @($taskName, $keepTaskName)) {
    if (Get-ScheduledTask -TaskName $tn -ErrorAction SilentlyContinue) {
        Unregister-ScheduledTask -TaskName $tn -Confirm:$false
        Write-Host "已移除旧任务 $tn" -ForegroundColor DarkGray
    }
}

# --- 3. 动作：用 wscript.exe 启动，全程无窗口 ---
#
# 为什么不用 powershell.exe -WindowStyle Hidden：
#   PowerShell 是控制台程序，Windows 会先创建控制台窗口、再处理
#   -WindowStyle Hidden，所以任务运行时仍会闪出一个黑框。
#   WshShell.Run(cmd, 0, False) 的 0 = SW_HIDE，
#   进程从创建那一刻起就没有窗口，不会闪。
# 注意：实际启动命令由下面的 New-LauncherVbs 生成，
# 这里不用 -WindowStyle Hidden（对控制台程序无效，详见下方注释）。

$vbsPaper = Join-Path $scriptDir 'run_hidden.vbs'
$vbsKeep  = Join-Path $scriptDir 'run_hidden_keepalive.vbs'

# VBS 内容保持纯 ASCII，用 ASCII 编码写盘，避免任何 BOM/编码坑。
# 用字符串数组逐行拼接，而不是 here-string —— here-string 里的
# 双引号和变量插值很容易写错（这个文件已经踩过一次）。
function New-LauncherVbs {
    param([string]$ScriptPath, [string]$ExtraArg = '')
    # VBS 字符串里要保留引号，必须写成两个连续引号（""）。
    # 这里用字符码拼接，避免在 PowerShell 里写嵌套同类引号被吞掉。
    $q  = [char]34
    $qq = [string]$q + [string]$q
    $cmdLine = 'powershell.exe -NoProfile -ExecutionPolicy Bypass -File ' +
               $qq + $ScriptPath + $qq + $ExtraArg
    $lines = @(
        "' Auto-generated by setup_scheduler.ps1 -- do not edit by hand.",
        "' Launches PowerShell with no visible window (SW_HIDE = 0).",
        'Option Explicit',
        'Dim sh, cmd',
        ('Set sh = CreateObject(' + $q + 'Wscript.Shell' + $q + ')'),
        ('cmd = ' + $q + $cmdLine + $q),
        'sh.Run cmd, 0, False'
    )
    return $lines -join "`r`n"
}

Set-Content -Path $vbsPaper -Value (New-LauncherVbs -ScriptPath $mainScript) -Encoding ASCII
Set-Content -Path $vbsKeep  -Value (New-LauncherVbs -ScriptPath $mainScript -ExtraArg ' -KeepAlive') -Encoding ASCII

$paperAction = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbsPaper`""
$keepAction  = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument "`"$vbsKeep`""

# --- 4. 触发器 ---
# Windows 计划任务没有"仅在指定星期开机时触发"这种触发器，只有
# "每次开机"和"每次登录"。要覆盖「周日晚上不关机、周一整天没开关机」
# 这种场景，必须额外加「固定时刻」触发器。
$bootTrigger = New-ScheduledTaskTrigger -AtStartup
$bootTrigger.Delay = 'PT3M'

$logonTrigger = New-ScheduledTaskTrigger -AtLogOn
$logonTrigger.Delay = 'PT3M'

$mondayTrigger   = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday  -At '10:00'
$thursdayTrigger = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Thursday -At '10:00'

$settings = New-ScheduledTaskSettingsSet `
    -AllowStartIfOnBatteries `
    -DontStopIfGoingOnBatteries `
    -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
    -MultipleInstances IgnoreNew `
    -StartWhenAvailable

$principal = New-ScheduledTaskPrincipal -UserId $env:USERNAME -LogonType Interactive -RunLevel Limited

Register-ScheduledTask `
    -TaskName $taskName `
    -Action $paperAction `
    -Trigger @($bootTrigger, $logonTrigger, $mondayTrigger, $thursdayTrigger) `
    -Settings $settings `
    -Principal $principal `
    -Description '开机/登录(延迟3分钟) + 周一周四10:00；当天已推送则跳过' | Out-Null

# --- 5. Keep Alive：开机时检查，脚本内限制每 30 天只做一次 ---
Register-ScheduledTask `
    -TaskName $keepTaskName `
    -Action $keepAction `
    -Trigger $bootTrigger `
    -Settings $settings `
    -Principal $principal `
    -Description '开机时检查，每 30 天触发一次 Keep Alive' | Out-Null

Write-Host "`n计划任务已安装`n" -ForegroundColor Green
Write-Host "【论文推送】$taskName" -ForegroundColor Cyan
Write-Host "  触发器  :"
Write-Host "    1. 开机+3分钟 / 登录+3分钟（等代理软件就绪）"
Write-Host "    2. 周一 10:00、周四 10:00（覆盖整天不开机的场景）"
Write-Host "  逻辑    : 仅当今天是周一或周四、且当天尚未推送时才真正触发"
Write-Host ""
Write-Host "【Keep Alive】$keepTaskName" -ForegroundColor Cyan
Write-Host "  触发    : 每次开机+3分钟（脚本内限制每 30 天只做一次）"
Write-Host ''
Write-Host "常用命令：" -ForegroundColor DarkGray
Write-Host "  查看状态  : Get-ScheduledTask -TaskName $taskName | Get-ScheduledTaskInfo"
Write-Host "  立即测试  : Start-ScheduledTask -TaskName $taskName"
Write-Host "  强制推送  : .\trigger_workflow.ps1 -Force"
Write-Host "  查看失败  : Get-Content .trigger_failures.log -Tail 20"
Write-Host "  删除      : Unregister-ScheduledTask -TaskName $taskName,\`$keepTaskName -Confirm:\`$false"
Write-Host ''
Write-Host "说明：所有触发器共享去重标记，一天只会收到一封邮件。" -ForegroundColor Yellow
